{% set name = "python-configuration" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd13d5f4c59bc3bd63bb3fefae3713812ac38f47273e78e804da7d17aa6475e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - config
    - config.contrib

about:
  home: https://github.com/tr11/python-configuration
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library to load configuration parameters from multiple sources and formats
  doc_url: https://python-configuration.readthedocs.io

extra:
  recipe-maintainers:
    - DanNixon
    - wiphoo
