{% set name = "python-configuration" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 750411cb92ca1e7a8973e7d9151a18b17fd4f7d234afddb21ad58bf10418cc40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - config
    - config.contrib

about:
  home: https://github.com/tr11/python-configuration
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library to load configuration parameters from multiple sources and formats
  doc_url: https://python-configuration.readthedocs.io

extra:
  recipe-maintainers:
    - DanNixon
    - wiphoo
