{% set name = "python-configuration" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a33324a361228f078485df8a059778b89eb353bdb52654df669439be21e74b25

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - config
    - config.contrib

about:
  home: "https://github.com/tr11/python-configuration"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A library to load configuration parameters from multiple sources and formats"
  doc_url: "https://python-configuration.readthedocs.io"

extra:
  recipe-maintainers:
    - DanNixon
